import { randomUUID } from "crypto";
import { storage } from "./storage";
import { searchNearby } from "./googlePlaces";
import { analyzeCompetitors } from "./ai";
import type { Report, Business, InsertReport } from "@shared/schema";

export async function runReportForBusiness(
  businessId: string,
  language: string = "en",
  providedBusiness?: Business
): Promise<Report> {
  const business = providedBusiness || await storage.getBusiness(businessId);

  if (!business) {
    throw new Error(`Business with ID ${businessId} not found`);
  }

  if (business.locationStatus === "pending" || business.latitude === null || business.longitude === null) {
    throw new Error(`Business "${business.name}" has pending location verification. Please verify the business location before generating a report.`);
  }

  const competitors = await searchNearby(
    business.latitude,
    business.longitude,
    business.type,
    1500
  );

  const aiAnalysis = await analyzeCompetitors(business, competitors, language);

  const html = generateReportHTML(business, competitors, aiAnalysis, language);

  // Only save report if not a temporary business
  if (!providedBusiness) {
    const insertReport: InsertReport = {
      businessId: business.id,
      businessName: business.name,
      competitors,
      aiAnalysis,
      html,
    };

    const report = await storage.saveReport(insertReport);
    return report;
  }

  // For temporary businesses, return report without saving
  return {
    id: 'temp-' + Date.now(),
    businessId: business.id,
    businessName: business.name,
    competitors,
    aiAnalysis,
    html,
    generatedAt: new Date(),
  };
}

function generateReportHTML(
  business: Business,
  competitors: { name: string; address: string; rating?: number; userRatingsTotal?: number; priceLevel?: string }[],
  aiAnalysis: string,
  language: string = "en"
): string {
  const translations: Record<string, any> = {
    en: {
      title: "Competitor Analysis Report",
      generated: "Generated",
      overview: "Overview",
      competitorsFound: "Competitors Found",
      avgRating: "Avg. Rating",
      totalReviews: "Total Reviews",
      nearbyCompetitors: "Nearby Competitors",
      table: {
        name: "Name",
        address: "Address",
        rating: "Rating",
        reviews: "Reviews",
        price: "Price"
      },
      noCompetitors: "No competitors found in the nearby area.",
      aiAnalysis: "AI Analysis",
      footer: "Generated by Local Competitor Analyzer"
    },
    pt: {
      title: "Relatório de Análise de Concorrência",
      generated: "Gerado em",
      overview: "Visão Geral",
      competitorsFound: "Concorrentes Encontrados",
      avgRating: "Classificação Média",
      totalReviews: "Total de Avaliações",
      nearbyCompetitors: "Concorrentes Próximos",
      table: {
        name: "Nome",
        address: "Morada",
        rating: "Classificação",
        reviews: "Avaliações",
        price: "Preço"
      },
      noCompetitors: "Não foram encontrados concorrentes na área próxima.",
      aiAnalysis: "Análise de IA",
      footer: "Gerado por Analisador de Concorrência Local"
    },
    es: {
      title: "Informe de Análisis de Competencia",
      generated: "Generado el",
      overview: "Visión General",
      competitorsFound: "Competidores Encontrados",
      avgRating: "Calif. Media",
      totalReviews: "Total de Reseñas",
      nearbyCompetitors: "Competidores Cercanos",
      table: {
        name: "Nombre",
        address: "Dirección",
        rating: "Calificación",
        reviews: "Reseñas",
        price: "Precio"
      },
      noCompetitors: "No se encontraron competidores en el área cercana.",
      aiAnalysis: "Análisis de IA",
      footer: "Generado por Analizador de Competencia Local"
    },
    fr: {
      title: "Rapport d'Analyse de la Concurrence",
      generated: "Généré le",
      overview: "Aperçu",
      competitorsFound: "Concurrents Trouvés",
      avgRating: "Note Moyenne",
      totalReviews: "Total des Avis",
      nearbyCompetitors: "Concurrents à Proximité",
      table: {
        name: "Nom",
        address: "Adresse",
        rating: "Note",
        reviews: "Avis",
        price: "Prix"
      },
      noCompetitors: "Aucun concurrent trouvé dans la zone à proximité.",
      aiAnalysis: "Analyse IA",
      footer: "Généré par Analyseur de Concurrence Locale"
    },
    de: {
      title: "Wettbewerbsanalysebericht",
      generated: "Erstellt am",
      overview: "Übersicht",
      competitorsFound: "Gefundene Wettbewerber",
      avgRating: "Durchschn. Bewertung",
      totalReviews: "Gesamtbewertungen",
      nearbyCompetitors: "Wettbewerber in der Nähe",
      table: {
        name: "Name",
        address: "Adresse",
        rating: "Bewertung",
        reviews: "Rezensionen",
        price: "Preis"
      },
      noCompetitors: "Keine Wettbewerber in der näheren Umgebung gefunden.",
      aiAnalysis: "KI-Analyse",
      footer: "Erstellt von Lokaler Wettbewerbsanalysator"
    }
  };

  const t = translations[language] || translations.en;

  const competitorRows = competitors
    .map(
      (c) => `
      <tr>
        <td style="padding: 12px; border-bottom: 1px solid #e5e7eb;">${c.name}</td>
        <td style="padding: 12px; border-bottom: 1px solid #e5e7eb;">${c.address}</td>
        <td style="padding: 12px; border-bottom: 1px solid #e5e7eb; text-align: center;">${c.rating ? c.rating.toFixed(1) : 'N/A'}</td>
        <td style="padding: 12px; border-bottom: 1px solid #e5e7eb; text-align: center;">${c.userRatingsTotal || 'N/A'}</td>
        <td style="padding: 12px; border-bottom: 1px solid #e5e7eb; text-align: center;">${c.priceLevel || 'N/A'}</td>
      </tr>
    `
    )
    .join("");

  return `
<!DOCTYPE html>
<html lang="${language}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${t.title} - ${business.name}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
      line-height: 1.6;
      color: #1f2937;
      background: #f9fafb;
      padding: 40px 20px;
    }
    .container {
      max-width: 900px;
      margin: 0 auto;
      background: white;
      border-radius: 12px;
      box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
      overflow: hidden;
    }
    .header {
      background: linear-gradient(135deg, #2563eb 0%, #1d4ed8 100%);
      color: white;
      padding: 40px;
    }
    .header h1 {
      font-size: 28px;
      margin-bottom: 8px;
    }
    .header p {
      opacity: 0.9;
      font-size: 14px;
    }
    .content {
      padding: 40px;
    }
    .section {
      margin-bottom: 32px;
    }
    .section h2 {
      font-size: 20px;
      color: #1f2937;
      margin-bottom: 16px;
      padding-bottom: 8px;
      border-bottom: 2px solid #e5e7eb;
    }
    .stats-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
      gap: 16px;
      margin-bottom: 24px;
    }
    .stat-card {
      background: #f3f4f6;
      padding: 20px;
      border-radius: 8px;
      text-align: center;
    }
    .stat-card .value {
      font-size: 32px;
      font-weight: bold;
      color: #2563eb;
    }
    .stat-card .label {
      font-size: 12px;
      color: #6b7280;
      text-transform: uppercase;
      letter-spacing: 0.05em;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      margin-top: 16px;
    }
    th {
      background: #f9fafb;
      padding: 12px;
      text-align: left;
      font-weight: 600;
      border-bottom: 2px solid #e5e7eb;
    }
    .analysis-box {
      background: #eff6ff;
      border-left: 4px solid #2563eb;
      padding: 24px;
      border-radius: 0 8px 8px 0;
      white-space: pre-wrap;
      font-size: 14px;
      line-height: 1.8;
    }
    .footer {
      text-align: center;
      padding: 24px;
      background: #f9fafb;
      color: #6b7280;
      font-size: 12px;
    }
    @media print {
      body { background: white; padding: 0; }
      .container { box-shadow: none; }
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>${t.title}</h1>
      <p>${business.name} | ${business.type.charAt(0).toUpperCase() + business.type.slice(1)} | ${t.generated}: ${new Date().toLocaleDateString()}</p>
    </div>
    
    <div class="content">
      <div class="section">
        <h2>${t.overview}</h2>
        <div class="stats-grid">
          <div class="stat-card">
            <div class="value">${competitors.length}</div>
            <div class="label">${t.competitorsFound}</div>
          </div>
          <div class="stat-card">
            <div class="value">${competitors.filter(c => c.rating).length > 0
      ? (competitors.filter(c => c.rating).reduce((sum, c) => sum + (c.rating || 0), 0) / competitors.filter(c => c.rating).length).toFixed(1)
      : 'N/A'}</div>
            <div class="label">${t.avgRating}</div>
          </div>
          <div class="stat-card">
            <div class="value">${competitors.reduce((sum, c) => sum + (c.userRatingsTotal || 0), 0).toLocaleString()}</div>
            <div class="label">${t.totalReviews}</div>
          </div>
        </div>
      </div>

      <div class="section">
        <h2>${t.nearbyCompetitors}</h2>
        ${competitors.length > 0 ? `
        <table>
          <thead>
            <tr>
              <th>${t.table.name}</th>
              <th>${t.table.address}</th>
              <th style="text-align: center;">${t.table.rating}</th>
              <th style="text-align: center;">${t.table.reviews}</th>
              <th style="text-align: center;">${t.table.price}</th>
            </tr>
          </thead>
          <tbody>
            ${competitorRows}
          </tbody>
        </table>
        ` : `<p style="color: #6b7280;">${t.noCompetitors}</p>`}
      </div>

      <div class="section">
        <h2>${t.aiAnalysis}</h2>
        <div class="analysis-box">${aiAnalysis}</div>
      </div>
    </div>

    <div class="footer">
      <p>${t.footer} | ${new Date().toISOString()}</p>
    </div>
  </div>
</body>
</html>
  `.trim();
}
